config/routes.rb
NestedForm::Application.routes.draw do
  resources :cricket_teams

  devise_for :users

  authenticated :user do
    root 'cricket_teams#index'
  end

  
  devise_scope :user do
   get "sign_in", to: "devise/sessions#new"
  end

end

app/models/cricket_team.rb
class CricketTeam < ActiveRecord::Base
	has_many :players
	accepts_nested_attributes_for :players, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

	def player_name
		players.collect{|p| p.name}.join(", ")
	end

end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :cricket_team
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/cricket_teams_controller.rb
class CricketTeamsController < ApplicationController
  before_action :set_cricket_team, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @cricket_teams = CricketTeam.all
    respond_with(@cricket_teams)
  end

  def show
    respond_with(@cricket_team)
  end

  def new
    @cricket_team = CricketTeam.new
    respond_with(@cricket_team)
  end

  def edit
  end

  def create
    @cricket_team = CricketTeam.new(cricket_team_params)
    @cricket_team.save
    redirect_to cricket_teams_path
  end

  def update
    @cricket_team.update(cricket_team_params)
    respond_with(@cricket_team)
  end

  def destroy
    @cricket_team.destroy
    respond_with(@cricket_team)
  end

  private
    def set_cricket_team
      @cricket_team = CricketTeam.find(params[:id])
    end

    def cricket_team_params
      params.require(:cricket_team).permit(:title, :content, players_attributes: [:id, :name, :content, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cricket_teams_helper.rb
module CricketTeamsHelper
end

app/views/cricket_teams/_form.html.erb
<%= nested_form_for @cricket_team do |f| %>
  <% if @cricket_team.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cricket_team.errors.count, "error") %> prohibited this cricket_team from being saved:</h2>

      <ul>
      <% @cricket_team.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>

  <%= f.fields_for :players do |player| %>
    <%= player.text_field :name %><br>
    <%= player.text_area :content %>
    <%= player.link_to_remove "Remove this player" %>
  <% end %>

  <p><%= f.link_to_add "Add a player", :players %></p>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cricket_teams/edit.html.erb
<h1>Editing cricket_team</h1>

<%= render 'form' %>

<%= link_to 'Show', @cricket_team %> |
<%= link_to 'Back', cricket_teams_path %>

app/views/cricket_teams/index.html.erb
<h1>Listing cricket_teams</h1>

<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Title</th>
      <th>Content</th>
      <th>Player name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cricket_teams.each_with_index do |cricket_team, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= cricket_team.title %></td>
        <td><%= cricket_team.content %></td>
        <td><%= cricket_team.player_name %></td>
        <td><%= link_to 'Edit', edit_cricket_team_path(cricket_team) %></td>
        <td><%= link_to 'Destroy', cricket_team, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cricket team', new_cricket_team_path %>

app/views/cricket_teams/new.html.erb
<h1>New cricket_team</h1>

<%= render 'form' %>

<%= link_to 'Back', cricket_teams_path %>

app/views/cricket_teams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @cricket_team.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @cricket_team.content %>
</p>

<%= link_to 'Back', cricket_teams_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NestedForm</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "nested_form","data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>

</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>